version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # location of package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"